### ISSUE TITLE
Consultation for 'regular paper accept'  on TSIPN.

### ISSUE THREAD

**Issue by wonlee2019** [ArefEinizade2/ProdSpecTemp#1]
Dear Aref.
How do you think the hard degree of TSIPN accept? And what about your paper how to go through the review process? 
I am looking forward to your respones.
Hornered, wonlee.

**Comment by ArefEinizade2** [comment]
Hello, and thank you for your question,

I think if your paper is relevant to extending the concepts of classical
signal processing and machine learning, the TSIPN could be a viable journal
to publish. From my experience, they have expert associate editors and
reviewers in these new and modern fields, e.g., Graph Signal Processing.
Besides, I honestly do not know how to describe the hardness of paper
acceptance. But I admit that their required quality is pretty high, and if
a paper gets rejected, they would give some helpful revisions for further
submissions or improvements. There are usually two or three revision stages
which, in some cases, they were very constructive to my papers which
needed much effort to improve the papers.

I wish you the best of luck with your publications,
Best regards,
Aref

**Comment by wonlee2019** [comment]
Thanks a lot!
